In [43]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.1.0'

In [6]:
df = pd.read_csv("housing.csv")

In [9]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [16]:
len(df.ocean_proximity.unique())

5

In [17]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [21]:
df[df.ocean_proximity == 'NEAR BAY'].median_house_value.mean()

259212.31179039303

In [26]:
tbd = df.total_bedrooms.mean()

In [23]:
df.total_bedrooms.head()

0     129.0
1    1106.0
2     190.0
3     235.0
4     280.0
Name: total_bedrooms, dtype: float64

In [28]:
df.total_bedrooms.fillna(tbd)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [29]:
tbd = df.total_bedrooms.mean()

In [30]:
tbd

537.8705525375618

In [31]:
island_df = df[df.ocean_proximity == 'ISLAND']

In [32]:
island_df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [36]:
island_df_sub = island_df[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [39]:
X = island_df_sub.values

In [47]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [73]:
X_transpose = X.T

In [81]:
XTX = X_transpose.dot(X)

In [82]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [83]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [84]:
y = np.array([950, 1300, 800, 1000, 1300])

In [86]:
w = np.dot(np.dot(XTX_inv, X_transpose), y) 

In [87]:
w

array([23.12330961, -1.48124183,  5.69922946])